image:
  name: tuanloc
  tag: service
port: 8080
target_port: 8080
database_username: cG9zdGdyZXM=
database_password: cG9zdGdyZXM=
database_host: 192.168.1.22
database_port: 5432
database_name: fast-storage-service
database_migration: false
database_initialization_data: false
keycloak_client_id: ZmFzdC1zdG9yYWdlLXNlcnZpY2U=
keycloak_client_secret: b1NHRkZZcFB5UGQ5V0RPck0yczVpamFsOFJ3SHM4Mlo=
keycloak_api_url: https://192.168.1.22:8443
keycloak_admin_username: YWRtaW4=
keycloak_admin_password: YWRtaW4=
account_active_host: https://polliwog-one-rarely.ngrok-free.app
nfs_host: 192.168.1.22
mount_folder: /mount/
smtp_host: smtp.office365.com
smtp_port: 587
outlook_username: username
outlook_password: cGFzc3dvcmQK
