FROM tuanloc/my_ubuntu:latest

EXPOSE 8080

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/go_app

ADD ./additional_source_code/ /additional_source_code/

CMD ["/app/go_app"]
