FROM golang:1.22.2-alpine as go

FROM tuanloc/my_ubuntu:latest

COPY --from=go /usr/local/go /usr/local/go
COPY --from=go /go /go

ENV GO_PATH="/usr/local/go"
ENV PATH="$PATH:$GO_PATH/bin"
ENV GO_ROOT="/go"
ENV PATH="$PATH:$GO_ROOT/bin"

EXPOSE 8080

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/go_app

ADD ./additional_source_code/ /additional_source_code/

CMD ["/app/go_app"]
