apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database_username: {{ .Values.database_username }}
  database_password: {{ .Values.database_password }}
  keycloak_client_id: {{ .Values.keycloak_client_id }}
  keycloak_client_secret: {{ .Values.keycloak_client_secret }}
  keycloak_admin_username: {{ .Values.keycloak_admin_username }}
  keycloak_admin_password: {{ .Values.keycloak_admin_password }}
  outlook_password: {{ .Values.outlook_password }}
